name: Build Plugin
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: ZIP the files
        uses: papeloto/action-zip@v1
        with:
          files: src/
          dest: TooManyPlayers.op
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: TooManyPlayers
          path: ${{ github.workspace }}/TooManyPlayers.op
